server:
  servlet:
    context-path: /seller
  port: 8082

#rpc.manager.url: http://localhost:8081/manager/
logging:
  level:
    com.googlecode.jsonrpc4j: debug

rpc:
  client:
    url: http://localhost:8081/manager/
    basePackage: com.xiaoming.api

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  cache:
    type: hazelcast
  activemq:
    broker-url: tcp://127.0.0.1:61616
    packages:
      trust-all: true
  datasource:
    url: jdbc:mysql://localhost:3306/saller?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
    jpa:
      show-sql: true