spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=123456&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
  activemq:
    broker-url: tcp://127.0.0.1:61616
  jms:
    pub-sub-domain: true
server:
  servlet:
    context-path: /manager
  port: 8081
swagger:
  groupName: manager
  basePackage: com.xiaoming.manager.controller

